command:
- python
- app.py


env: 
  - name: KA_ENDPOINT_NAME
    valueFrom: ${ka_endpoint_name}
  - name: ONLINE_STORE
    valueFrom: ${lakebase_instance}

   # TODO: find a way to not hardcode these: 
  - name: EXPERIMENT_PATH
    valueFrom: /Users/jitesh.soni@databricks.com/ka-ce79c9c6-dev-experiment
  - name: APP_URL
    value: ""